<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFmixton\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFmixton/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFmixton.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFmixton\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFmixton\appProdProjectContainer(array(
    'container.build_hash' => 'Fmixton',
    'container.build_id' => '5561eedc',
    'container.build_time' => 1538913677,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFmixton');
