<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RequestMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RequestMatcher.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Http/AccessMap.php';

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/finance'), array(0 => 'ROLE_FINANCE'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/student'), array(0 => 'ROLE_STUDENT'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/assistent'), array(0 => 'ROLE_ASSIST'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/director'), array(0 => 'ROLE_DIRECT'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/tech'), array(0 => 'ROLE_TECH'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/report/server'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);

return $instance;
