<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';

return $this->services['form.registry'] = new \Symfony\Component\Form\FormRegistry(array(0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Form\\EventsType' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\EventsType']) ? $this->services['AppBundle\Form\EventsType'] : $this->services['AppBundle\Form\EventsType'] = new \AppBundle\Form\EventsType()) && false ?: '_'};
}, 'AppBundle\\Form\\Login_Form_template' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\Login_Form_template']) ? $this->services['AppBundle\Form\Login_Form_template'] : $this->services['AppBundle\Form\Login_Form_template'] = new \AppBundle\Form\Login_Form_template()) && false ?: '_'};
}, 'AppBundle\\Form\\academic_year_form' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\academic_year_form']) ? $this->services['AppBundle\Form\academic_year_form'] : $this->services['AppBundle\Form\academic_year_form'] = new \AppBundle\Form\academic_year_form()) && false ?: '_'};
}, 'AppBundle\\Form\\add_assistant_form' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\add_assistant_form']) ? $this->services['AppBundle\Form\add_assistant_form'] : $this->services['AppBundle\Form\add_assistant_form'] = new \AppBundle\Form\add_assistant_form()) && false ?: '_'};
}, 'AppBundle\\Form\\application_form' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\application_form']) ? $this->services['AppBundle\Form\application_form'] : $this->services['AppBundle\Form\application_form'] = new \AppBundle\Form\application_form()) && false ?: '_'};
}, 'AppBundle\\Form\\edit_profile_form' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\edit_profile_form']) ? $this->services['AppBundle\Form\edit_profile_form'] : $this->services['AppBundle\Form\edit_profile_form'] = new \AppBundle\Form\edit_profile_form()) && false ?: '_'};
}, 'AppBundle\\Form\\finance_add_payment' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\finance_add_payment']) ? $this->services['AppBundle\Form\finance_add_payment'] : $this->services['AppBundle\Form\finance_add_payment'] = new \AppBundle\Form\finance_add_payment()) && false ?: '_'};
}, 'AppBundle\\Form\\report_problem_form' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\report_problem_form']) ? $this->services['AppBundle\Form\report_problem_form'] : $this->services['AppBundle\Form\report_problem_form'] = new \AppBundle\Form\report_problem_form()) && false ?: '_'};
}, 'AppBundle\\Form\\report_student' => function () {
    return ${($_ = isset($this->services['AppBundle\Form\report_student']) ? $this->services['AppBundle\Form\report_student'] : $this->services['AppBundle\Form\report_student'] = new \AppBundle\Form\report_student()) && false ?: '_'};
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ${($_ = isset($this->services['form.type.entity']) ? $this->services['form.type.entity'] : $this->load('getForm_Type_EntityService.php')) && false ?: '_'};
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ${($_ = isset($this->services['form.type.choice']) ? $this->services['form.type.choice'] : $this->load('getForm_Type_ChoiceService.php')) && false ?: '_'};
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ${($_ = isset($this->services['form.type.form']) ? $this->services['form.type.form'] : $this->load('getForm_Type_FormService.php')) && false ?: '_'};
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['form.type_extension.form.http_foundation']) ? $this->services['form.type_extension.form.http_foundation'] : $this->load('getForm_TypeExtension_Form_HttpFoundationService.php')) && false ?: '_'};
    yield 1 => ${($_ = isset($this->services['form.type_extension.form.validator']) ? $this->services['form.type_extension.form.validator'] : $this->load('getForm_TypeExtension_Form_ValidatorService.php')) && false ?: '_'};
    yield 2 => ${($_ = isset($this->services['form.type_extension.upload.validator']) ? $this->services['form.type_extension.upload.validator'] : $this->load('getForm_TypeExtension_Upload_ValidatorService.php')) && false ?: '_'};
    yield 3 => ${($_ = isset($this->services['form.type_extension.csrf']) ? $this->services['form.type_extension.csrf'] : $this->load('getForm_TypeExtension_CsrfService.php')) && false ?: '_'};
    yield 4 => ${($_ = isset($this->services['form.type_extension.form.data_collector']) ? $this->services['form.type_extension.form.data_collector'] : $this->load('getForm_TypeExtension_Form_DataCollectorService.php')) && false ?: '_'};
}, 5), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['form.type_extension.repeated.validator']) ? $this->services['form.type_extension.repeated.validator'] : $this->services['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()) && false ?: '_'};
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['form.type_extension.submit.validator']) ? $this->services['form.type_extension.submit.validator'] : $this->services['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()) && false ?: '_'};
}, 1)), new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['form.type_guesser.validator']) ? $this->services['form.type_guesser.validator'] : $this->load('getForm_TypeGuesser_ValidatorService.php')) && false ?: '_'};
    yield 1 => ${($_ = isset($this->services['form.type_guesser.doctrine']) ? $this->services['form.type_guesser.doctrine'] : $this->load('getForm_TypeGuesser_DoctrineService.php')) && false ?: '_'};
}, 2), NULL)), ${($_ = isset($this->services['form.resolved_type_factory']) ? $this->services['form.resolved_type_factory'] : $this->load('getForm_ResolvedTypeFactoryService.php')) && false ?: '_'});
