<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ydrexq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ydrexq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4ydrexq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4ydrexq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4ydrexq\appDevDebugProjectContainer(array(
    'container.build_hash' => '4ydrexq',
    'container.build_id' => 'bd321240',
    'container.build_time' => 1538913665,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4ydrexq');
