<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dormapplication extends \AppBundle\Entity\Dormapplication implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'card_id', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'surname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'nationality', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'academic_year', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'birthday', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'city', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'phoneNr', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'department', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fathersname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fatherssurname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fathersphoneNr', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fathersJob', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'mothersname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'motherssurname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'mothersphoneNr', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'mothersJob', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'parentMaritStatus', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'isaccepted', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'type'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'card_id', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'surname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'nationality', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'academic_year', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'birthday', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'city', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'phoneNr', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'department', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fathersname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fatherssurname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fathersphoneNr', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'fathersJob', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'mothersname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'motherssurname', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'mothersphoneNr', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'mothersJob', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'parentMaritStatus', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'isaccepted', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Dormapplication' . "\0" . 'type'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dormapplication $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardId', []);

        return parent::getCardId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardId($card_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardId', [$card_id]);

        return parent::setCardId($card_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNr', []);

        return parent::getPhoneNr();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNr($phoneNr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNr', [$phoneNr]);

        return parent::setPhoneNr($phoneNr);
    }

    /**
     * {@inheritDoc}
     */
    public function getFathersphoneNr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFathersphoneNr', []);

        return parent::getFathersphoneNr();
    }

    /**
     * {@inheritDoc}
     */
    public function setFathersphoneNr($fathersphoneNr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFathersphoneNr', [$fathersphoneNr]);

        return parent::setFathersphoneNr($fathersphoneNr);
    }

    /**
     * {@inheritDoc}
     */
    public function getMothersphoneNr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMothersphoneNr', []);

        return parent::getMothersphoneNr();
    }

    /**
     * {@inheritDoc}
     */
    public function setMothersphoneNr($mothersphoneNr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMothersphoneNr', [$mothersphoneNr]);

        return parent::setMothersphoneNr($mothersphoneNr);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentMaritStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentMaritStatus', []);

        return parent::getParentMaritStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentMaritStatus($parentMaritStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentMaritStatus', [$parentMaritStatus]);

        return parent::setParentMaritStatus($parentMaritStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality($nationality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNr]);

        return parent::setPhoneNumber($phoneNr);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcademicYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcademicYear', []);

        return parent::getAcademicYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcademicYear($academic_year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcademicYear', [$academic_year]);

        return parent::setAcademicYear($academic_year);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartment', []);

        return parent::getDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartment($department)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartment', [$department]);

        return parent::setDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function getFathersname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFathersname', []);

        return parent::getFathersname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFathersname($fathersname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFathersname', [$fathersname]);

        return parent::setFathersname($fathersname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFatherssurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFatherssurname', []);

        return parent::getFatherssurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFatherssurname($fatherssurname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFatherssurname', [$fatherssurname]);

        return parent::setFatherssurname($fatherssurname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFathersPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFathersPhoneNumber', []);

        return parent::getFathersPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setFathersPhoneNumber($fathersphoneNr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFathersPhoneNumber', [$fathersphoneNr]);

        return parent::setFathersPhoneNumber($fathersphoneNr);
    }

    /**
     * {@inheritDoc}
     */
    public function getMothersname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMothersname', []);

        return parent::getMothersname();
    }

    /**
     * {@inheritDoc}
     */
    public function setMothersname($mothersname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMothersname', [$mothersname]);

        return parent::setMothersname($mothersname);
    }

    /**
     * {@inheritDoc}
     */
    public function getMothersSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMothersSurname', []);

        return parent::getMothersSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setMothersSurname($motherssurname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMothersSurname', [$motherssurname]);

        return parent::setMothersSurname($motherssurname);
    }

    /**
     * {@inheritDoc}
     */
    public function getMothersPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMothersPhoneNumber', []);

        return parent::getMothersPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setMothersPhoneNumber($mothersphoneNr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMothersPhoneNumber', [$mothersphoneNr]);

        return parent::setMothersPhoneNumber($mothersphoneNr);
    }

    /**
     * {@inheritDoc}
     */
    public function getFathersJob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFathersJob', []);

        return parent::getFathersJob();
    }

    /**
     * {@inheritDoc}
     */
    public function setFathersJob($fathersJob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFathersJob', [$fathersJob]);

        return parent::setFathersJob($fathersJob);
    }

    /**
     * {@inheritDoc}
     */
    public function getMothersJob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMothersJob', []);

        return parent::getMothersJob();
    }

    /**
     * {@inheritDoc}
     */
    public function setMothersJob($mothersJob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMothersJob', [$mothersJob]);

        return parent::setMothersJob($mothersJob);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaritalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaritalStatus', []);

        return parent::getMaritalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaritalStatus($parentMaritStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaritalStatus', [$parentMaritStatus]);

        return parent::setMaritalStatus($parentMaritStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsaccepted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsaccepted', []);

        return parent::isIsaccepted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsaccepted($isaccepted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsaccepted', [$isaccepted]);

        return parent::setIsaccepted($isaccepted);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
