<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AcademicYear extends \AppBundle\Entity\AcademicYear implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'year', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'semester', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'dorm_application', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'member_id', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'payment_id', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'start_date', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'end_date'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'year', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'semester', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'dorm_application', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'member_id', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'payment_id', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'start_date', '' . "\0" . 'AppBundle\\Entity\\AcademicYear' . "\0" . 'end_date'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AcademicYear $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear($year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemester()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemester', []);

        return parent::getSemester();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemester($semester)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemester', [$semester]);

        return parent::setSemester($semester);
    }

    /**
     * {@inheritDoc}
     */
    public function getDormApplication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDormApplication', []);

        return parent::getDormApplication();
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberId', []);

        return parent::getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberId($member_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberId', [$member_id]);

        return parent::setMemberId($member_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentId($payment_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentId', [$payment_id]);

        return parent::setPaymentId($payment_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate($start_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$start_date]);

        return parent::setStartDate($start_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate($end_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$end_date]);

        return parent::setEndDate($end_date);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
